[project]
name = "easylist"
version = "0.1.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.4",
    "loguru>=0.7.2",
    "pydantic[email]>=2.9.2",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.0",
]

[tool.uv]
dev-dependencies = ["ruff<1.0.0,>=0.2.2"]
package = true

[tool.pyright]
reportInvalidTypeForm = false
reportMissingTypeDefinition = false

[tool.ruff]
exclude = ["assets"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D101",
    "D107",
    "I001",
    "D100",
    "W292",
    "W293",
    "D103",
    "D104",
    "D106",
    "D102",
    "D105",
]

fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.setuptools]
packages = ["easylist", "assets"]
